#!/usr/bin/env bash

# Usage:
# mkdir test-dir
# cd test-dir
# \curl https://raw.github.com/vinodpandey/blog/master/django-recycled | bash

echo 'Creating virtual environment'
virtualenv-2.7 --no-site-packages .
source bin/activate
echo 'Installing Django'
pip install Django==1.5.0
echo 'Creating Django Project'
django-admin.py startproject project
deactivte


